version: "3"

services:
  nginx:
     #定义主机名
     container_name: nginx
     #使用的镜像
     image: nginx:latest
     #容器的映射端口
     ports:
       - "80:80"
       - "443:443"
     #定义挂载点
     #ssl文件夹下用来配置https
     volumes:
       - ./nginx/html:/usr/share/nginx/html
       - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/conf.d:/etc/nginx/conf.d
       - ./nginx/logs:/var/log/nginx
       - ./nginx/ssl/alphaclass:/etc/ssl/imctalphaclass/
     #docker 重启后，容器自启动
     restart: always
  # tomcat
  tomcat:
    container_name: tomcat
    image: tomcat:9.0.41-jdk8-corretto
    links:
      -  mysql:mysql
    # webapps挂载war包
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
  flask:
    container_name: flask
    build: ./flask
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    # init文件夹下放置初始化sql文件
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data/mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
    ]
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=alphaclass"
      - "TZ=Asia/Shanghai"


# todo
# 主程序修改，数据库地址改成主机名